### PR TITLE
Fixed package scripts when no files exist

### PR DESCRIPTION
**Pull request by mribichich**
Fixed clean script. Added `-f` argument to `rm` command

Switch the `;` for `&&` in the scripts

### CODE REVIEW

**Comment by mribichich** [comment]
The -f allow not to fail when the files dont exist. Thats the only reason I put it. Because if you dont have the files, the build script fails

**Comment by bcherny** [comment]
@mribichich It gives a warning, but should still succeed. Can you be more specific - what do you mean by "files", what is the specific script that fails? Even better, what are the steps to reproduce the failure?

**Comment by mribichich** [comment]
This is the output of the command:

```
$ npm test

> react2angular@1.0.6 pretest C:\github\mribichich\react2angular
> npm run build


> react2angular@1.0.6 build C:\github\mribichich\react2angular
> npm run clean && tsc -d -m es2015 && mv ./index.js ./index.es2015.js && tsc -m commonjs -t es5


> react2angular@1.0.6 clean C:\github\mribichich\react2angular
> rm ./*.d.ts && rm ./*.map && exit 0

rm: cannot remove './*.d.ts': No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react2angular@1.0.6 clean: `rm ./*.d.ts && rm ./*.map && exit 0`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react2angular@1.0.6 clean script 'rm ./*.d.ts && rm ./*.map && exit 0'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react2angular package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm ./*.d.ts && rm ./*.map && exit 0
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react2angular
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react2angular
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ld\AppData\Roaming\npm-cache\_logs\2017-03-15T23_25_00_062Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react2angular@1.0.6 build: `npm run clean && tsc -d -m es2015 && mv ./index.js ./index.es2015.js && tsc -m commonjs -t es5`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react2angular@1.0.6 build script 'npm run clean && tsc -d -m es2015 && mv ./index.js ./index.es2015.js && tsc -m commonjs -t es5'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react2angular package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && tsc -d -m es2015 && mv ./index.js ./index.es2015.js && tsc -m commonjs -t es5
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react2angular
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react2angular
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ld\AppData\Roaming\npm-cache\_logs\2017-03-15T23_25_00_149Z-debug.log
npm ERR! Test failed.  See above for more details.
```

**Comment by bcherny** [comment]
`rm ./*.d.ts && rm ./*.map && exit 0` is the output after your change. If you revert your changes that are in this PR and run `npm test` again, what is the output?

**Comment by mribichich** [comment]
Its the same, if I use `rm ./*.d.ts; rm ./*.map; exit 0`

```
$ npm run clean

> react2angular@1.0.6 clean C:\github\mribichich\react2angular
> rm ./*.d.ts; rm ./*.map; exit 0

rm: cannot remove './*.d.ts;': No such file or directory
rm: cannot remove 'rm': No such file or directory
rm: cannot remove './*.map;': No such file or directory
rm: cannot remove 'exit': No such file or directory
rm: cannot remove '0': No such file or directory
```

If you dont have the same thing, probably is a problem in windows.

**Comment by bcherny** [comment]
See the last 2 lines of your output - the issue isn't that the command fails, the issue is that everything after the initial `rm` gets treated as a filename to delete. Are you using CMD? Powershell?

**Comment by mribichich** [comment]
I'm using git bash because `rm` it's a linux cmd.

Dont worry. I'm going to close this and revert it. Its clearly a windows problem.
sorry for the time

**Comment by bcherny** [comment]
One thing to try is to put the globs in quotes, and see if that helps.

Ie. `rm "./*.d.ts"; rm "./*.map"; exit 0`

**Comment by mribichich** [comment]
It doesn't seen to work, it's the way windows interprets the command
thanks anyways

**Comment by bcherny** [comment]
Ok - if you figure it out, please comment back here. I'm sure other Windows users will find it helpful.

**Pull request closed without merging**
